Resources:
    EKSCluster:
        Type: AWS::EKS::Cluster
        Properties:
            Name: eshani-cluster-node
            Version: "1.25"
            RoleArn: "arn:aws:iam::388328004932:role/AWSEKSRole"
            ResourcesVpcConfig:
                SecurityGroupIds:
                - sg-0d8315f2e7a43714e
                SubnetIds:
                - subnet-0a31af885cfd8721d
                - subnet-01b356a04735bdf93 
                EndpointPublicAccess: true
                EndpointPrivateAccess: false
                PublicAccessCidrs: [ "0.0.0.0/0" ]
    EKSNodegroup:
      Type: 'AWS::EKS::Nodegroup'
      DependsOn: EKSCluster
      Properties:
        ClusterName: eshani-cluster-node
        NodegroupName: eshani-node
        NodeRole: "arn:aws:iam::388328004932:role/eks-node-group"
        ScalingConfig:
          MinSize: 2
          DesiredSize: 2
          MaxSize: 3
        Labels:
          Key1: Value1
          Key2: Value2
        Subnets:
          - subnet-0a31af885cfd8721d
          - subnet-01b356a04735bdf93
